name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version, LTS is a good choice

      - name: Install dependencies
        run: npm ci # Or npm install

      - name: Build React application
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Deploy the 'build' directory
          # cname: your.custom.domain.com # Uncomment if you have a custom domain
          # publish_branch: gh-pages # Default is gh-pages
          # keep_files: false
          # force_orphan: true
